sudo: false
dist: trusty
language: java
install: true
jdk:
  - oraclejdk8

script:
  - "mvn clean"
  - "mvn verify sonar:sonar"

addons:
  sonarcloud:
    organization: "igornb-github"
    token:
      secure: "Vqo2dTzhN254s4Pr2tuQJfu/LzfUyq+IHAvLzSCvqDysM5qAZxPr3VHltFyv5Jgk0Ov5/t4r58EuSVULHQ7yw2HOq+LdfoENremst9sAulzPjYiYGywJ9SWWAJAqmoQtvL1j/Jt1bJxelG5m8UWg2grWZBbHqH29IJ0HK7HBIUhltEJoldaIYLv8Pb0QlcbdljMCzpXbTTIvxlRKswe5n+uM3hNOZUYyKa9eUsbFTCQCYB0KyBOJPih1T6oswPei1e3BrHl35TnzTSWzUQb80wygJNbx0/vbKbvPmXNapz4twHEOy6vBvs3SAtumNvovZWwFhd0bw81EkaL6o34qXZ4QgqazmsdN0oFOhwwe+XCt1eqCIoqYY5W2yNyAdsJLuScqAWTQxicTVXBk/Ymk/MOuYgZRSPgqrd2WOQrLWMEuSBd7qtPQNTFHuX6vkWyONxF3xvMszI9LzSOghYrttS8es5YDvwafXLdzGA10etXWpHwgkIzNZh8mJeAgqPyv4njHczi6GSjle6/2WQ0140a0EIaxrEBLIvde6MEqGwm2a/xfewq4fiOE7A5QVzJlyBuXiMZm7/2TMyYzdxLp/ncxD0VgCq0nt3iPnYiHG7s1PJFXSyJcm1sZxmxq/UoGMG1DfX0yB6eeVRoHolcIqkhjn9WnV/f2R1+V0mTCJQU="

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache