version: '2'

services:
  libby:
    container_name: libby
    environment:
      - POSTGRES_DB=libby
      - SPRING_PROFILES_ACTIVE=dockerCompose, springDataJpa
    build: .
    ports:
      - 8090:8090
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:alpine
    environment:
      - POSTGRES_DB=libby
      - POSTGRES_PASSWORD=pwd
    expose:
      - 5432
    ports:
      - 5432:5432